export const GENERATE_SET_OF_PIN = "GENERATE_SET_OF_PIN";
export const SAVE_SET_OF_PIN = "SAVE_SET_OF_PIN";
export const DELETE_SET_OF_PIN = "DELETE_SET_OF_PIN";
export const UPDATE_SET_OF_PIN = "UPDATE_SET_OF_PIN";
